server:
  port: 8081

spring:
  application:
    name: fraud
  datasource:
    username: postgres
    url: jdbc:postgresql://localhost:5432/frauds
    password: 25052001Dm.
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true